version: '3.5'
services:
   nexus:
     image: sonatype/nexus3:3.23.0
     volumes: 
       - ./nexus-data:/nexus-data
     ports:
       - 8081:8081
       - 8123:8123
       - 5000:5000
       - 8082:8082
       - 8083:8083
       - 8181:8181     
volumes: 
    nexus-data:
